scss_files: 'src/styles/**/*.scss'

exclude: 'src/styles/_bower.scss'

severity: error

linters:

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true
    max_elements: 1

  ElsePlacement:
    enabled: true
    style: new_line

  ExtendDirective:
    enabled: true

  HexLength:
    style: long

  Indentation:
      character: tab
      width: 1

  NameFormat:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  QualifyingElement:
    enabled: true

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: Should only be used with javascript, apply a different class for styling purposes.

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SpaceAfterComma:
    enabled: true
    style: no_space

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding : true

  StringQuotes:
    enabled: true
    style: double_quotes

  TrailingZero:
    enabled: true
